### ISSUE TITLE
这个比赛

### ISSUE THREAD

**Issue by Anonymous06180719** [0xFFD700-alter/rm#1]
请问有这个比赛的好些的代码吗，我去年被老师拉去参加过，但是没这方面知识，现在学了一点，想看看别人怎么写的。

**Comment by 0xFFD700-alter** [comment]
[https://github.com/JiaxiSun/Intelligent-Distributed-Wireless-Radio-Map-Construction](url)
这是去年比赛 REAL队伍 的开源方案，希望对你们有帮助

**Comment by Anonymous06180719** [comment]
太谢谢你啦




Mang&nbsp;Koon&nbsp;Ming
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "0xFFD700-alter/rm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月18日(星期一) 凌晨0:09
***@***.***&gt;;
抄送:&nbsp;"Mang Koon ***@***.******@***.***&gt;;
主题:&nbsp;Re: [0xFFD700-alter/rm] 这个比赛 (Issue #1)





 
https://github.com/JiaxiSun/Intelligent-Distributed-Wireless-Radio-Map-Construction
 这是去年比赛 REAL队伍 的开源方案，希望对你们有帮助
